package crawler.web.web_crawler.model;

public enum IssueType {


    MISSING_ALT,
    EMPTY_ALT,
    ALT_TOO_SHORT,
    ALT_TOO_LONG,
    ALT_IS_FILENAME,
    NO_LAZY_LOADING,

    MISSING_CONTROLS,
    MISSING_CAPTIONS,
    MISSING_ARIA_LABEL,
    MISSING_TITLE,
    AUTOPLAY,
    AUTOPLAY_WITHOUT_CAPTIONS,
    AUTOPLAY_MUTED,
    IFRAME_MISSING_TITLE,

    MISSING_LANGUAGE,
    LANGUAGE_IS_EMPTY,
    INVALID_LANGUAGE_CODE,

    TITLE_NOT_EXISTS,
    TITLE_IS_EMPTY,
    TITLE_IS_NOT_MEANINGFUL,
    TITLE_IS_GENERIC,

    MISSING_HEADINGS,
    H1_APPEARS_MORE_THAN_ONCE,
    H1_DOES_NOT_APPEAR,
    HEADING_STRUCTURE_INVALID
}
